
name: herald
namespace: herald

replicaCount: 1

heraldConfig:
  port: 8000
  temp_dir: "./tmp"
  task_store_backend:
    endpoint: http://minio.herald:9000
    region: local
    forcePathStyle: true
    bucket: s3-test
    credentials:
      accessKeyId: minio
      secretAccessKey: password
  backends:
    minio_s3:
      protocol: s3
    openstack_swift:
      protocol: swift
  service_accounts: []
  buckets:
    s3-test:
      backend: minio_s3
      config:
        endpoint: http://minio.herald:9000
        region: local
        forcePathStyle: true
        bucket: s3-test
        credentials:
          accessKeyId: minio
          secretAccessKey: password
  replicas: []

image:
  repository: ghcr.io/expnt/herald
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}
deploymentAnnotations: {}
podSecurityContext: {}

extraEnvFrom: {}
extraEnv:
  - name: CONFIG_FILE_PATH
    value: "/etc/herald/herald-config.yaml"
  - name: AUTH_TYPE
    value: "none"
  - name: SENTRY_DSN
    value: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: web-tls
    #   hosts:
    #     - chart-example.local

volumeMounts:
  - name: herald
    mountPath: /etc/herald/
    readOnly: true

volumes:
  - name: herald
    configMap:
      name: herald

helmhookjob:
  enabled: false

  annotations: {}

  imagePullSecrets: []

  image:
    repository: alpine
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: IfNotPresent

  command: null

  extraEnvFrom: {}

  extraEnv: []

  resources: {}
