include:
  - project: 'devops/gitlab-ci-templates'
    ref: main
    file: 'docker.yml'
  - project: 'devops/gitlab-ci-templates'
    ref: main
    file: 'terraform.yml'

docker:
  extends: .docker
  variables:
    DOCKER_EXTRA_ARGS: |
      --build-arg RELEASE
  only:
    - main
    - merge_requests

terraform:
  extends: .terraform
  needs:
    - docker
  only:
    - main
  variables:
    KUBE_CTX: 'expo-test'
  environment:
    name: staging
