.env_export: &env_export
  before_script:
    - |
      apt update && apt install -y curl
      curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash
      apt-get update && apt-get install -y infisical
      infisical export --domain https://infisical.exponent.ch/api --env=$INFISICAL_ENV > .env
      export $(grep -E '^[^#]*=' .env | xargs)

include:
  - project: 'devops/gitlab-ci-templates'
    ref: main
    file: 'docker.yml'
  - project: "devops/gitlab-ci-templates"
    ref: main
    file: "terragrunt.yml"

docker:
  extends: .docker
  variables:
    DOCKER_DOCKERFILE: "Dockerfile"
    DOCKER_BUILD_CONTEXT: "."
  only:
    - main
    - dev
    - staging
    - merge_requests

deploy-staging:
  extends: .terragrunt
  image: denoland/deno:debian
  needs:
    - docker
  only:
    - main
    - staging
  variables:
    TERRAGRUNT_PATH: "deploy/app/stg"
    KUBE_CTX: expo-test
    INFISICAL_ENV: "staging"
  <<: *env_export
  environment:
    name: staging

deploy-dev:
  extends: .terragrunt
  image: denoland/deno:debian
  needs:
    - docker
  only:
    - dev
    - main
  variables:
    TERRAGRUNT_PATH: "deploy/app/dev"
    KUBE_CTX: expo-test
    INFISICAL_ENV: "development"
  <<: *env_export
  environment:
    name: development
