include:
  - project: 'devops/gitlab-ci-templates'
    ref: main
    file: 'docker.yml'
  - project: 'devops/gitlab-ci-templates'
    ref: main
    file: 'terraform.yml'

docker:
  extends: .docker
  variables:
    DOCKER_EXTRA_ARGS: |
      --build-arg RELEASE
  only:
    - main
    - merge_requests

terraform:
  extends: .terraform
  before_script:
    - curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash
    - apt-get update && apt-get install -y infisical
    - infisical export --domain https://infisical.exponent.ch/api --env prd --path /
  needs:
    - docker
  only:
    - main
  variables:
    KUBE_CTX: 'expo-test'
  environment:
    name: staging
