repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: tests/res
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*\.json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: deno-fmt
        name: Deno format
        language: system
        entry: bash -c 'deno fmt'
        pass_filenames: false
        types:
          - ts
      - id: deno-lint
        name: Deno lint
        language: system
        entry: bash -c 'deno lint'
        pass_filenames: false
        types:
          - ts
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.3
    hooks:
      - id: tofu_fmt
      - id: tofu_checkov
        args:
          - --args=--skip-check CKV_TF_1
          - --args=--skip-check CKV_TF_2
          - --args=--skip-check CKV_SECRET_9
          - --args=--skip-check CKV_GCP_62
          - --args=--skip-check CKV_GCP_114
          - --args=--skip-check CKV_K8S_*
          - --args=--skip-path deploy/app/chart-generic
          - --args=--skip-path deploy/app/chart-/generic
      - id: tofu_tflint
        args:
          - --args=--disable-rule terraform_module_pinned_source
      # - id: tofu_trivy
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--exclude=SC2154,SC2181"]
