repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: tests/res
      - id: check-ast
      - id: check-json
        exclude: .vscode/.*\.json
      - id: check-toml
      - id: check-yaml
        exclude: ^(charts/templates/.*\.yaml)$
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: deno-fmt
        name: Deno format
        language: system
        entry: bash -c 'deno fmt'
        pass_filenames: false
        types:
          - ts
      - id: deno-lint
        name: Deno lint
        language: system
        entry: bash -c 'deno lint'
        pass_filenames: false
        types:
          - ts
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.3
    hooks:
      - id: tofu_fmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--exclude=SC2154,SC2181"]
