services:
  minio:
    image: minio/minio:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_REGION_NAME: local
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: "test"

  swift:
    image: openstackswift/saio:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8080:8080"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    restart: unless-stopped
    environment:
      CONFIG_FILE_PATH: "herald-compose.yaml"
    volumes:
      - .:/app
