port: 8000
temp_dir: "./tmp"
backends:
  minio_s3:
    protocol: s3
  openstack_swift:
    protocol: swift
buckets:
  s3-test:
    backend: minio_s3
    config:
      endpoint: "http://minio:9000"
      region: local
      forcePathStyle: true
      credentials:
        accessKeyId: minio
        secretAccessKey: password
  swift-test:
    backend: openstack_swift
    config:
      auth_url: "http://swift:8080/auth/v1.0"
      storage_url: "http://swift:8080"
      credentials:
        username: "test:tester"
        password: "testing"
        project_name: "your-project-name"
        user_domain_name: "Default"
        project_domain_name: "Default"
      container: "your-container-name"
