port: 8000
temp_dir: "./tmp"
backends:
  minio_s3:
    protocol: s3
  openstack_swift:
    protocol: swift

task_store_backend:
  endpoint: "http://localhost:9000"
  region: local
  forcePathStyle: true
  bucket: task-store
  credentials:
    accessKeyId: minio
    secretAccessKey: password

service_accounts:
  - name: "system:serviceaccount:dev-s3-herald:default"
    buckets:
      - s3-test
      - s3-mirror-test
      - swift-mirror-test
      - iac-s3

buckets:
  s3-test:
    backend: minio_s3
    config:
      endpoint: "http://localhost:9000"
      region: local
      forcePathStyle: true
      bucket: s3-test
      credentials:
        accessKeyId: minio
        secretAccessKey: password
  s3-mirror-test:
    backend: minio_s3
    config:
      endpoint: "http://localhost:9000"
      region: local
      forcePathStyle: true
      bucket: s3-mirror-test
      credentials:
        accessKeyId: minio
        secretAccessKey: password
  iac-s3:
    backend: minio_s3
    config:
      endpoint: "http://localhost:9000"
      region: local
      forcePathStyle: true
      bucket: iac-s3
      credentials:
        accessKeyId: minio
        secretAccessKey: password
  swift-test:
    backend: openstack_swift
    config:
      auth_url: https://api.pub1.infomaniak.cloud/identity/v3
      credentials:
        username: PCU-RP63UPV
        password: c.0eWLr02R--6l9N/#M05!ykGU
        project_name: PCP-RP63UPV
        user_domain_name: Default
        project_domain_name: Default
      container: swift-test
      region: dc3-a
  swift-mirror-test:
    backend: openstack_swift
    config:
      auth_url: https://api.pub1.infomaniak.cloud/identity/v3
      credentials:
        username: PCU-RP63UPV
        password: c.0eWLr02R--6l9N/#M05!ykGU
        project_name: PCP-RP63UPV
        user_domain_name: Default
        project_domain_name: Default
      container: swift-mirror-test
      region: dc3-a

replicas:
  - name: s3-swift-replica
    backend: minio_s3
    config:
      endpoint: "http://localhost:9090"
      region: local
      forcePathStyle: true
      bucket: swift-mirror-test
      credentials:
        accessKeyId: minio
        secretAccessKey: password
  - name: swift-replica
    backend: openstack_swift
    config:
      auth_url: https://api.pub1.infomaniak.cloud/identity/v3
      credentials:
        username: PCU-RP63UPV
        password: c.0eWLr02R--6l9N/#M05!ykGU
        project_name: PCP-RP63UPV
        user_domain_name: Default
        project_domain_name: Default
      container: "s3-mirror-test"
      region: dc3-a
  - name: s3-replica
    backend: minio_s3
    config:
      endpoint: "http://localhost:9090"
      region: local
      forcePathStyle: true
      bucket: s3-mirror-test
      credentials:
        accessKeyId: minio
        secretAccessKey: password
