apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "herald.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "herald.labels" . | nindent 4 }}
data:
  herald-config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
