apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
data:
  herald-config.yaml:
    {{- with .Values.heraldConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
