apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "herald.fullname" . }}
  labels:
    {{- include "herald.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "herald.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "herald.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: herald
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG_FILE_PATH
              value: /etc/herald/herald-dev.yaml
            - name: AUTH_TYPE
              value: none
            - name: SENTRY_DSN
              value: {{ .Values.sentry_dsn | quote }}
          volumeMounts:
            - name: herald
              mountPath: /etc/herald/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
      volumes:
        - name: herald
          configMap:
            name: herald
