replicaCount: 2

image:
  repository: ghcr.io/expnt/herald
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: my-registry-secret

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 80m
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-tls
      hosts:
        - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /health-check
    port: http

readinessProbe:
  httpGet:
    path: /health-check
    port: http
