# checkov:skip=CKV_DOCKER_2: Health check managed elsewhere
# checkov:skip=CKV_DOCKER_3: User settings managed elsewhere
FROM denoland/deno:alpine-2.3.5

WORKDIR /app

# Copy deno.jsonc and deno.lock for dependency caching
COPY deno.jsonc deno.lock ./

# Copy the rest of the source code
COPY ./src ./src

# Cache dependencies
RUN deno cache src/main.ts

ENTRYPOINT ["deno"]
CMD ["serve", "-A", "--unstable-kv", "src/main.ts"]
