FROM denoland/deno:alpine-2.3.5

WORKDIR /app

# Copy deno.jsonc and deno.lock for dependency caching
COPY deno.jsonc deno.lock ./

# Cache dependencies
RUN deno install

# Copy the rest of the source code
COPY ./src ./src

ENTRYPOINT ["deno"]
CMD ["run", "-A", "src/main.ts"]
