name: Release Management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release-test
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Bump and Get Version
        id: version
        run: |
          npx cz bump --yes
          NEW_VERSION=$(npx cz version -p)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .cz.yaml
          git commit -m "ci: bump version to ${{ env.NEW_VERSION }}"
          git push origin main

  create-release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        if: github.ref == 'refs/pull' || github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}${{ github.ref != 'refs/heads/main' && '-test' || '' }}
          release_name: Release ${{ env.NEW_VERSION }}${{ github.ref != 'refs/heads/main' && ' (Test)' || '' }}
          body: |
            Changelog for version ${{ env.NEW_VERSION }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    needs: [bump-version, create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/herald:${{ env.NEW_VERSION }}
          push: true

  delete-test-releases:
    if: github.event.pull_request.merged == true && github.base_ref == 'release-test'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Test Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          releases=$(gh api repos/${{ github.repository_owner }}/herald/releases --paginate)
          echo "$releases" | jq '.[] | select(.tag_name | contains("-test")) | .id' | while read release_id; do
            gh api --method DELETE "repos/${{ github.repository_owner }}/herald/releases/$release_id"
          done
