name: test suite
run-name: test suite for ${{ github.event.pull_request.title || github.ref }}
on:
  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: |
          Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate).
          This disables all but the test-full jobs.
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DENO_VERSION: 2.2.3
  GHJK_VERSION: "v0.2.1"
  GHJK_ENV: "ci"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            full:
              - '.github/workflows/tests.yml'
              - 'src/**'
              - 'tests/**'
              - 'examples/**'
    outputs:
      full: ${{ steps.filter.outputs.full }}

  pre-commit:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Install tofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method deb
          rm -f install-opentofu.sh

      - shell: bash
        run: |
          # ghjk p resolve
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
          deno --version
          pre-commit run --all-files
          # SKIP=ghjk-resolve pre-commit run --show-diff-on-failure --color=always --all-files

  test-full:
    needs: [changes]
    if: ${{ needs.changes.outputs.full == 'true' && !(github.event_name == 'workflow_dispatch' && inputs.tmate_enabled) && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Download Install Script
        run: curl -fsSL "https://raw.github.com/metatypedev/ghjk/$GHJK_VERSION/install.sh" -o install.sh
      - name: Execute Install Script
        run: yes | bash install.sh
      - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: echo "BASH_ENV=$HOME/.local/share/ghjk/env.sh" >> "$GITHUB_ENV"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install tofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method deb
          rm -f install-opentofu.sh
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: setup start-server-and-test
        run: npm install -g start-server-and-test
      - name: load herald.yaml file
        run: |
          rm -rf herald.yaml
          echo "${{ secrets.HERALD_CONFIG }}" > herald.yaml
      - shell: bash
        env:
          AUTH_TYPE: "none"
          LOG_LEVEL: "DEBUG"
          ENV: "DEV"
        run: |
          ghjk x dev-compose all

          deno install

          # ghjk x setup-auth
          npx start-server-and-test 'deno run -A --unstable-kv src/main.ts' http://0.0.0.0:8000/ 'deno test -A'
