name: test suite
run-name: test suite for ${{ github.event.pull_request.title || github.ref }}
on:
  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: |
          Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate).
          This disables all but the test-full jobs.
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            full:
              - '.github/workflows/tests.yml'
              - 'src/**'
              - 'tests/**'
              - 'examples/**'
    outputs:
      full: ${{ steps.filter.outputs.full }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install OpenTofu
      run: |
        wget https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_linux_amd64.zip
        unzip tofu_1.6.0_linux_amd64.zip
        sudo mv tofu /usr/local/bin/
    - shell: bash
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files


  build-docker:
      needs: changes
      if: ${{ needs.changes.outputs.full == 'true' && !(github.event_name == 'workflow_dispatch' && inputs.tmate_enabled) }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push herald
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/herald:latest
